import {
  WHALES_POOLS,
  VERSION_TYPES,
  KNOWN_COLLECTIONS,
  TONCENTER_API_KEY,
  TONCENTER_RPC,
  NODES_INFO,
  IPFS_GATEWAY,
} from '../private/config.js'

const config = {
  WHALES_POOLS,
  VERSION_TYPES,
  KNOWN_COLLECTIONS,
  TONCENTER_API_KEY,
  TONCENTER_RPC,
  NODES_INFO,
  IPFS_GATEWAY,
}

export default config